// Scheduled-match ("fixture") data model.
// Distinct from the parsed Cricsheet Match model in types.ts -- a fixture is a
// match that has been created and scheduled but not yet played, so it has no
// innings/deliveries/result. Written to /data/fixtures/<id>.json by
// app/api/fixtures/route.ts and read back by lib/store/fixture-store.ts.

import type { Gender } from "./types";

export type FixtureCreationType = "friendly" | "league" | "tournament";
export type BallType = "Red" | "White" | "Pink";
export type DayNight = "Day" | "Night" | "Day/Night";
export type RetirementRule = "none" | "retired-out" | "retired-not-out";
export type FixtureStatus = "Scheduled" | "Live" | "Completed";

export interface FixtureTournament {
  type: FixtureCreationType;
  name: string;
}

export interface FixtureVenue {
  name: string;
  city?: string;
}

export interface FixtureRules {
  oversPerInnings: number | null;
  powerplayOvers: number | null;
  superOver: boolean;
  dls: boolean;
  wideRuns: number;
  noBallRuns: number;
  freeHit: boolean;
  retirement: RetirementRule;
  retirementOverThreshold?: number;
}

/** A team as configured for this specific fixture -- squad is a plain player-name list, not a persisted team roster. */
export interface FixtureTeam {
  name: string;
  squad: string[];
}

export interface FixturePlayingXI {
  team: string; // matches FixtureTeam.name
  players: string[]; // exactly 11, all drawn from that team's squad
  captain: string;
  viceCaptain?: string;
  wicketKeeper: string;
}

export interface FixtureToss {
  winner: string; // matches one of the two team names
  decision: "bat" | "bowl";
}

export interface Fixture {
  id: string;
  name: string;
  createdAt: string;
  status: FixtureStatus;
  tournament: FixtureTournament;
  format: string;
  overs: number | null;
  ballType: BallType;
  gender: Gender;
  ageGroup: string;
  matchType: string;
  venue: FixtureVenue;
  date: string;
  startTime: string;
  timeZone: string;
  dayNight: DayNight;
  rules: FixtureRules;
  /** Populated progressively by the pre-match setup flow (/matches/[id]/setup/*), absent until each stage is completed. */
  teams?: [FixtureTeam, FixtureTeam];
  playingXI?: [FixturePlayingXI, FixturePlayingXI];
  toss?: FixtureToss;
  /** Set only for fixtures generated by the Tournament module -- links this scheduled match back to its owning Tournament. Absent for standalone matches created via /matches/new. */
  tournamentId?: string;
  /** Display label for this fixture's place in the tournament, e.g. "Round 4", "Quarterfinal", "Semifinal", "Final". Only meaningful when tournamentId is set. */
  round?: string;
}

/** Shape submitted to POST /api/fixtures -- server assigns id/createdAt/status. */
export type FixtureDraft = Omit<Fixture, "id" | "createdAt" | "status">;

/** Shape accepted by PATCH /api/fixtures/[id] -- any subset of the post-creation setup fields. */
export type FixturePatch = Partial<Pick<Fixture, "teams" | "playingXI" | "toss" | "status">>;
