// Static searchable index for Settings Home's "Search settings" field --
// every individual control across all ten categories, so a query like
// "password" or "theme" jumps straight to the right category instead of
// only matching the ten top-level category names.

import type { SettingsCategory } from "./types";

export interface SearchEntry {
  label: string;
  category: SettingsCategory;
}

export const SETTINGS_SEARCH_INDEX: SearchEntry[] = [
  { label: "Name", category: "profile" },
  { label: "Username", category: "profile" },
  { label: "Email", category: "profile" },
  { label: "Mobile Number", category: "profile" },
  { label: "Date of Birth", category: "profile" },
  { label: "Country", category: "profile" },
  { label: "Bio", category: "profile" },
  { label: "Organisation", category: "profile" },
  { label: "Change Password", category: "account" },
  { label: "Two-Factor Authentication", category: "account" },
  { label: "Linked Accounts", category: "account" },
  { label: "Session Management", category: "account" },
  { label: "Active Devices", category: "account" },
  { label: "Sign Out", category: "account" },
  { label: "Delete Account", category: "account" },
  { label: "Default Landing Page", category: "preferences" },
  { label: "Date Format", category: "preferences" },
  { label: "Time Format", category: "preferences" },
  { label: "Time Zone", category: "preferences" },
  { label: "Measurement Units", category: "preferences" },
  { label: "Default Tournament Format", category: "preferences" },
  { label: "Default Overs", category: "preferences" },
  { label: "Default Team Sorting", category: "preferences" },
  { label: "Push Notifications", category: "notifications" },
  { label: "Email Notifications", category: "notifications" },
  { label: "SMS Notifications", category: "notifications" },
  { label: "Tournament Updates", category: "notifications" },
  { label: "Match Reminders", category: "notifications" },
  { label: "Live Scoring Alerts", category: "notifications" },
  { label: "Marketing", category: "notifications" },
  { label: "Theme", category: "appearance" },
  { label: "Accent Colour", category: "appearance" },
  { label: "Font Size", category: "appearance" },
  { label: "Display Density", category: "appearance" },
  { label: "Reduce Animations", category: "appearance" },
  { label: "Preferred Formats", category: "cricket-preferences" },
  { label: "Favourite Teams", category: "cricket-preferences" },
  { label: "Favourite Players", category: "cricket-preferences" },
  { label: "Favourite Tournaments", category: "cricket-preferences" },
  { label: "Default Scoring Preference", category: "cricket-preferences" },
  { label: "Preferred Statistics", category: "cricket-preferences" },
  { label: "Privacy Controls", category: "privacy-security" },
  { label: "Blocked Users", category: "privacy-security" },
  { label: "Data Sharing", category: "privacy-security" },
  { label: "Analytics Consent", category: "privacy-security" },
  { label: "Export Personal Data", category: "privacy-security" },
  { label: "Delete My Data", category: "privacy-security" },
  { label: "App Permissions", category: "privacy-security" },
  { label: "Storage Used", category: "storage-downloads" },
  { label: "Downloaded Scorecards", category: "storage-downloads" },
  { label: "Downloaded Reports", category: "storage-downloads" },
  { label: "Downloaded Analytics", category: "storage-downloads" },
  { label: "Clear Cache", category: "storage-downloads" },
  { label: "App Version", category: "about" },
  { label: "Release Notes", category: "about" },
  { label: "Licences", category: "about" },
  { label: "Privacy Policy", category: "about" },
  { label: "Terms of Service", category: "about" },
  { label: "Help Centre", category: "about" },
  { label: "Contact Support", category: "about" },
  { label: "Report a Bug", category: "about" },
  { label: "Feedback", category: "about" },
  { label: "Feature Flags", category: "app-configuration" },
  { label: "New Scoring Engine", category: "app-configuration" },
  { label: "Beta Analytics", category: "app-configuration" },
  { label: "AI Insights", category: "app-configuration" },
  { label: "Experimental Features", category: "app-configuration" },
  { label: "API Endpoint", category: "app-configuration" },
  { label: "Debug Mode", category: "app-configuration" },
  { label: "Offline Mode", category: "app-configuration" },
  { label: "Sync Preferences", category: "app-configuration" },
  { label: "Developer Options", category: "app-configuration" },
];
